### ISSUE TITLE
Image URLs

### ISSUE THREAD

**Issue by jericahuang** [gmatilly/teacozy#3]
Totally fine that you're using direct codecademy web URLs for these images. However I would recommend learning about linking images with relative paths (download the image to your repository and set the URL to its relative path in your file structure) if you haven't already.

https://github.com/gmatilly/teacozy/blob/master/resources/css/style.css#L96
https://github.com/gmatilly/teacozy/blob/master/resources/css/style.css#L60
https://github.com/gmatilly/teacozy/blob/master/index.html#L13
... and others in your HTML.

**Comment by gmatilly** [comment]
ah ha. This whole time I have been using the links. I will do this moving forward. Thank you.
